# Netlify configuration for Astro site
[build]
  # Build command for Astro
  command = "npm run build"
  # Output directory where Astro builds the site
  publish = "dist"

[build.environment]
  # Node.js version (recommended for Astro)
  NODE_VERSION = "18"

# Redirects for SPA-like behavior (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Build processing settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true