backend:
  name: github
  repo: https://github.com/Brahadeesh2003/prj-on   # your repo
  branch: main                               # or master
  auth_scope: repo                                   
media_folder: "public/images/blog"
public_folder: "/images/blog"

# The src attribute for uploaded media will begin with /images/blog

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime", required: true }
      - { 
          label: "Category", 
          name: "category", 
          widget: "select", 
          options: ["Digital Validation", "Paperless Validation", "GxP Compliance", "Industry Insights", "Case Studies", "Technology"],
          default: "Digital Validation"
        }
      - { label: "Author", name: "author", widget: "string", default: "GoVal Team" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: true, hint: "Brief description for blog listing page" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "SEO Description", name: "description", widget: "text", required: false, hint: "Meta description for SEO" }
      - { label: "Tags", name: "tags", widget: "list", default: ["validation", "digital"], required: false }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }